apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "helm.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
type: Opaque
data:
  SecretId: {{ required ".Values.secrets.SecretId is required" .Values.secrets.SecretId | b64enc | quote }}
  SecretKey: {{ required ".Values.secrets.SecretKey is required" .Values.secrets.SecretKey | b64enc | quote }}
