apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "helm.fullname" . }}"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.env }}
  {{ $k | quote }}: {{ $v | toString | b64enc | quote }}
  {{- else }}
  noop: {{ required "No env!" .Values.env.noop }}
  {{- end }}
